name: 'Semantic Release Lite: Generate changelog'
description: Generates a changelog based on commit messages
inputs:
  breaking-change-keywords:
    description: If the commit message extended body starts with one of these prefixes (one per line, case sensitive) then a breaking change release will be made
    required: true
    default: BREAKING CHANGE
  minor-types:
    description: Same as main action
    required: false
  patch-types:
    description: Same as main action
    required: false
  trivial-types:
    description: Same as main action
    required: false
  last-tag:
    description: Last tag we released
  stay-at-zero:
    description: If we're currently at version 0.x (or no version at all) then this can be set to true to stay at version 0.x with our releases.
    default: 'false'
  from:
    description: "Commit to start from. Default: beginning of time."
  until:
    description: "Commit to stop at. Default: the commit that got checked out."
runs:
  using: node20
  main: generate-changelog.js
