name: Prerelease
description: Refreshes the `next` tag
inputs:
  changelog:
    description: changelog
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: >
        git config user.email "semantic-release-lite-bot.vcnga@passmail.net" &&
        git config user.name "Semantic Release Lite bot"

    - shell: bash
      run: git tag --force -m "Update with ${{ github.sha }}" next

    - shell: bash
      run: git push --tags --force

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        prerelease: true
        generateReleaseNotes: false
        makeLatest: false
        updateOnlyUnreleased: true
        name: Upcoming release
        commit: ${{ github.sha }}
        body: |
          This tag is merely a changelog preview and should not be used in your actions :exclamation:
          
          -----
          
          ${{ inputs.changelog }}
        tag: next
