name: Release stable
description: Releases changes to the branch
inputs:
  changelog:
    description: changelog
    required: true
  major:
    required: true
    description: major version
  minor:
    required: true
    description: minor version
  patch:
    required: true
    description: patch version
  issues-closed:
    description: Issues closed by the release
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        path: release
        ref: release

    - shell: bash
      working-directory: release
      run: >
        git config user.email "github-actions[bot]@users.noreply.github.com" &&
        git config user.name "github-actions[bot]"

    - shell: bash
      working-directory: release
      run: rm -rvf * && cp -vr ../dist/* . && echo "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}" > VERSION

    - shell: bash
      working-directory: release
      run: git add .

    - shell: bash
      working-directory: release
      run: git commit -m "Sync with ${{ github.sha }}"

    - shell: bash
      working-directory: release
      id: last-commit
      run: echo "sha=$(git log -n 1 --pretty=format:%H)" >> $GITHUB_OUTPUT

    - shell: bash
      working-directory: release
      run: git tag -m "Sync with ${{ github.sha }}" v${{ inputs.major }} --force

    - shell: bash
      working-directory: release
      run: git tag -m "Sync with ${{ github.sha }}" v${{ inputs.major }}.${{ inputs.minor }} --force

    - shell: bash
      working-directory: release
      run: git tag -m "Sync with ${{ github.sha }}" v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}

    - shell: bash
      working-directory: release
      run: git push

    - shell: bash
      working-directory: release
      run: git push --tags --force

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        prerelease: false
        generateReleaseNotes: false
        makeLatest: false
        commit: ${{ steps.last-commit.outputs.sha }}
        body: Alias for `v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}`
        tag: v${{ inputs.major }}

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        prerelease: false
        generateReleaseNotes: false
        makeLatest: false
        commit: ${{ steps.last-commit.outputs.sha }}
        body: Alias for `v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}`
        tag: v${{ inputs.major }}.${{ inputs.minor }}

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: false
        prerelease: false
        generateReleaseNotes: false
        commit: ${{ steps.last-commit.outputs.sha }}
        body: ${{ inputs.changelog }}
        tag: v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}

    - name: Notify
      if: ${{ inputs.issues-closed }}
      uses: ./dist/notify
      with:
        tag: v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}
        issues: ${{ inputs.issues-closed }}
