name: Dry run
on:
  - pull_request
jobs:
  dryrun:
    runs-on: ubuntu-latest
    name: Dry run
    permissions:
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Build
        uses: ./.github/actions/build

      - uses: ./dist
        name: Parse release
        id: parse-release
        with:
          minor-types: |
            feat: Features
          patch-types: |
            fix: Bug Fixes
          trivial-types: |
            chore: Maintenance
            deps: Dependency updates
            ci: CI & Build
            build: CI & Build
            refactor: Refactors
            docs: Documentation
