on:
  push:
    branches:
      - master
      - stable
name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    permissions:
      packages: read
      contents: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Build
        uses: ./.github/actions/build

      - name: Get changelog source commit
        uses: ./.github/actions/changelog-src
        id: changelog-src

      - name: Generate changelog
        uses: ./dist/generate-changelog
        id: changelog
        with:
          minor-types: |
            feat: Features
          patch-types: |
            fix: Bug Fixes
          trivial-types: |
            chore: Maintenance
            deps: Dependency updates
            ci: CI & Build
            build: CI & Build
            refactor: Refactors
            docs: Documentation
          from: ${{ steps.changelog-src.outputs.sha }}

      - name: Get next tag
        uses: ./dist/next-tag
        id: next-tag
        if: ${{ steps.changelog.outputs.should-release }}
        with:
          last-tag: ${{ steps.last-tag.outputs.last-tag }}
          release-type: ${{ steps.changelog.outputs.release-type }}
          stay-at-zero: true

      - name: Release
        uses: ./.github/actions/release-stable
        if: ${{ steps.changelog.outputs.should-release && github.ref_name == 'stable' }}
        with:
          major: ${{ steps.next-tag.outputs.major }}
          minor: ${{ steps.next-tag.outputs.minor }}
          patch: ${{ steps.next-tag.outputs.patch }}
          changelog: ${{ steps.changelog.outputs.changelog }}
          issues-closed: ${{ steps.changelog.outputs.issues-closed }}

      - name: Generate next tag
        if: ${{ steps.changelog.outputs.should-release && github.ref_name == 'master' }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: true
          generateReleaseNotes: false
          makeLatest: false
          updateOnlyUnreleased: true
          name: Upcoming release
          commit: ${{ github.sha }}
          body: ${{ steps.changelog.outputs.changelog }}
          tag: next
